apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: Copy of Caikit TGIS ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"
  name: caikit-tgis-runtime-copy
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
  containers:
    - args:
        - --model-name=/mnt/models/artifacts/
      command:
        - text-generation-launcher
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: quay.io/modh/text-generation-inference@sha256:aebf545d8048a59174f70334dc90c6b97ead4602a39cb7598ea68c8d199168a2
      name: kserve-container
    - env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: RUNTIME_GRPC_ENABLED
          value: "false"
        - name: RUNTIME_HTTP_ENABLED
          value: "true"
      image: quay.io/modh/caikit-tgis-serving@sha256:2c7eef73708b5d73de33153459ac7238fdcf517cdc3544c775981f5814b4b6ed
      name: transformer-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: caikit
